#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
title: Kevin Zeng
description: Ph.D. Candidate specializing in Deep Reinforcement Learning, Deep Reduced-Order Systems Modeling
github:
  about_me_url: https://k-zeng.github.io/ABOUT-ME
  my_projects_url: https://k-zeng.github.io/MY-PROJECTS
  resume_url: https://raw.githubusercontent.com/k-zeng/k-zeng.github.io/main/_documents/Zeng_Resume.pdf
  linkedin_url: https://www.linkedin.com/in/kevin-zeng-82b0b2224
  publications_url: https://k-zeng.github.io/PUBLICATIONS
